kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" 
parameters:
  diskformat: thin
  datastore: esx_cluster2_ds02
provisioner: kubernetes.io/vsphere-volume
